# Generated by Django 5.2.7 on 2025-10-14 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('private', 'Private'), ('conference', 'Conference'), ('shared', 'SharedDesk')], max_length=16)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_start', models.DateTimeField()),
                ('slot_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_code', models.CharField(max_length=20, unique=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.rooms')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.teams')),
            ],
        ),
        migrations.AddField(
            model_name='teams',
            name='members',
            field=models.ManyToManyField(related_name='teams', to='bookings.users'),
        ),
        migrations.CreateModel(
            name='BookingAttendees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='bookings.bookings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.users')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bookings',
            constraint=models.UniqueConstraint(fields=('room', 'slot_start'), name='unique_room_slot'),
        ),
        migrations.AddConstraint(
            model_name='bookingattendees',
            constraint=models.UniqueConstraint(fields=('booking', 'user'), name='unique_booking_user'),
        ),
    ]
